## Assignmet for the financial year 2017-2018

### Importing libraries

In [28]:
import pandas as pd
from IPython.display import display
import numpy as np

### Loading the dataset

In [29]:
df = pd.read_csv('district_level_mapping_2017.csv', low_memory = False)

In [30]:
df.shape

(375136, 20)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375136 entries, 0 to 375135
Data columns (total 20 columns):
 #   Column                                               Non-Null Count   Dtype  
---  ------                                               --------------   -----  
 0   Division Code                                        374488 non-null  float64
 1   Division Description                                 374488 non-null  object 
 2   Treasury Code                                        374488 non-null  float64
 3   Treasury                                             375136 non-null  object 
 4   Grant Number                                         375136 non-null  object 
 5   Grant Head Description                               375136 non-null  object 
 6   Major Head Code                                      375136 non-null  int64  
 7   Major Head Description                               372904 non-null  object 
 8   Scheme Code                                          3

In [32]:
df.sample(10)

Division Code Division Description  Treasury Code     Treasury  \
188505         4300.0        LUCKNOW COLL.           48.0        KHERI   
202872         1400.0            MORADABAD           92.0      SAMBHAL   
219897         4900.0             FAIZABAD           49.0     FAIZABAD   
92206           200.0           SAHARANPUR            2.0   SAHARANPUR   
310662          800.0                 AGRA            8.0         AGRA   
326347         4300.0        LUCKNOW COLL.           60.0   LUCKNOW-JB   
50599          3300.0                BASTI           33.0        BASTI   
249650         2300.0          JHANSI-MAIN           23.0  JHANSI-MAIN   
331658         2700.0             VARANASI           27.0     VARANASI   
283577          800.0                 AGRA            9.0     MAINPURI   

       Grant Number                             Grant Head Description  \
188505           49                         महिला एवं बाल कल्याण विभाग   
202872           49                         महिला एवं बाल कल्याण विभाग   
219897           49                         महिला एवं बाल कल्याण विभाग   
92206            21                                खाद्य तथा रसद विभाग   
310662           72                     शिक्षा विभाग (माध्यमिक शिक्षा)   
326347           79  समाज कल्याण विभाग (विकलांग एवं पिछड़ा वर्ग कल्...   
50599            14          कृषि तथा अन्य सम्बद्ध विभाग (पंचायती राज)   
249650           49                         महिला एवं बाल कल्याण विभाग   
331658           80  समाज कल्याण विभाग(समाज कल्याण एवं अनुसूचित जात...   
283577           60                                           वन विभाग   

        Major Head Code                             Major Head Description  \
188505             2235                         सामाजिक सुरक्षा तथा कल्याण   
202872             2235                         सामाजिक सुरक्षा तथा कल्याण   
219897             2235                         सामाजिक सुरक्षा तथा कल्याण   
92206              2408                         खाद्य भण्डारण तथा भांडागार   
310662             2204                           खेल कूद तथा युवा सेवायें   
326347             2235                         सामाजिक सुरक्षा तथा कल्याण   
50599              2515                         अन्य ग्राम विकास कार्यक्रम   
249650             2235                         सामाजिक सुरक्षा तथा कल्याण   
331658             2225  अनुसूचित जातियों, अनुसूचित जनजातियों तथा अन्य ...   
283577             2406                                वानिकी तथा वन्य जीव   

          Scheme Code                            Scheme Code Description  \
188505  2235021020102      समन्वित बाल विकास योजना (के.60/रा.40-के.+रा.)   
202872  2235021020102      समन्वित बाल विकास योजना (के.60/रा.40-के.+रा.)   
219897  2235021020104  समन्वित बाल विकास के लिए जिला स्तरीय स्टाफ की ...   
92206   2408010010300             अधिष्ठान व्यय (अधिप्राप्ति तथा पूर्ति)   
310662  2204001020400                            राष्ट्रीय सेना छात्र दल   
326347  2235021010300    मुख्यालय / मण्डलीय /जिला कार्यालयों का अधिष्ठान   
50599   2515001010300                                जिला पंचायत प्रशासन   
249650  2235021020122  किशोर न्याय बोर्ड की स्थापना (के.35/रा.65-के.+...   
331658  2225012771300  अनुसूचित जातियों के व्यक्तियों के लिये राज्य स...   
283577  2406010010400                                           अधिष्ठान   

        Standard Object Code                      Standard Object Description  \
188505                    49                                    चिकित्सा व्यय   
202872                    49                                    चिकित्सा व्यय   
219897                     6                                       अन्य भत्ते   
92206                     16        व्यावसायिक तथा विशेष सेवाओं के लिए भुगतान   
310662                     9                                      विद्युत देय   
326347                    11                  लेखन सामग्री और फार्मों की छपाई   
50599                      1                                             वेतन   
249650                    17      

In [33]:
df.isnull().sum()

Division Code                                           648
Division Description                                    648
Treasury Code                                           648
Treasury                                                  0
Grant Number                                              0
Grant Head Description                                    0
Major Head Code                                           0
Major Head Description                                 2232
Scheme Code                                               0
Scheme Code Description                                   0
Standard Object Code                                      0
Standard Object Description                               0
Plan / Non-Plan                                           0
Voted / Charged                                           0
fiscal_year                                               0
Progressive Allotment                                     0
Actual Progressive Expenditure upto mont

In [60]:
df['Provisional Current Month Expenditure(November)'].unique()

array([0])

In [61]:
df = df[['Grant Head Description', 'Progressive Allotment', 'Total Expenditure Upto Month (November)', '% A/E']]

In [62]:
df.sample(10)

Grant Head Description  Progressive Allotment  \
360616  संस्थागत वित्त विभाग (स्टाम्प एवं पंजीकरण)                    0.0   
59251         कृषि तथा अन्य सम्बद्ध विभाग ((पशुधन)                30000.0   
192028                  महिला एवं बाल कल्याण विभाग                    0.0   
80889         कृषि तथा अन्य सम्बद्ध विभाग ((पशुधन)                25000.0   
37761           कृषि तथा अन्य सम्बद्ध विभाग (कृषि)                    0.0   
24939           कृषि तथा अन्य सम्बद्ध विभाग (कृषि)              1500000.0   
246456                  महिला एवं बाल कल्याण विभाग                99000.0   
350797                          सैनिक कल्याण विभाग                 2000.0   
171258                                 न्याय विभाग               150000.0   
291608    वित्त विभाग (लेखा परीक्षा, अल्प-बचत आदि)                 8000.0   

        Total Expenditure Upto Month (November)   % A/E  
360616                                      0.0    0.00  
59251                                   30000.0  100.00  
192028                                   5270.0    0.00  
80889                                   25000.0  100.00  
37761                                       0.0    0.00  
24939                                 1342254.0   89.48  
246456                                  94189.0   95.14  
350797                                   2000.0  100.00  
171258                                  60318.0   40.21  
291608                                   8000.0  100.00

In [34]:
# Separating primary school data from df
primary_school_df = df[df['Grant Head Description'] == 'शिक्षा विभाग (प्राथमिक शिक्षा)']

In [35]:
primary_school_df.shape

(4808, 20)

In [36]:
primary_school_df['Major Head Code'].unique()

array([2071, 2202, 2204, 4202])

In [37]:
primary_school_df['Major Head Description'].unique()

array(['पेंशन तथा अन्य सेवा निवृत्ति हित लाभ', 'सामान्य शिक्षा',
       'खेल कूद तथा युवा सेवायें', nan], dtype=object)

In [38]:
primary_school_df = primary_school_df[primary_school_df['Major Head Description'] == 'सामान्य शिक्षा']

In [39]:
primary_school_df.shape

(4520, 20)

In [40]:
primary_school_df['Major Head Code'].unique()

array([2202])

In [41]:
pd.set_option('display.max_columns', None)
display(primary_school_df.sample(10))

Division Code Division Description  Treasury Code         Treasury  \
301748         3200.0            GORAKHPUR           35.0           DEORIA   
301465         5000.0                GONDA           51.0         BAHRAICH   
299996         2800.0             MIRZAPUR           72.0          BHADOHI   
300830         2700.0             VARANASI           27.0         VARANASI   
301430         2700.0             VARANASI           27.0         VARANASI   
298415         2600.0                BANDA           25.0  SADAR TRY-HMRPR   
300337         2000.0         KANPUR NAGAR           84.0          KANNAUJ   
300972         4300.0        LUCKNOW COLL.           60.0       LUCKNOW-JB   
299531         4300.0        LUCKNOW COLL.           47.0           HARDOI   
299610         2300.0          JHANSI-MAIN           58.0         LALITPUR   

       Grant Number          Grant Head Description  Major Head Code  \
301748           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
301465           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
299996           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
300830           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
301430           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
298415           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
300337           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
300972           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
299531           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
299610           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   

       Major Head Description    Scheme Code  \
301748         सामान्य शिक्षा  2202011120400   
301465         सामान्य शिक्षा  2202011120103   
299996         सामान्य शिक्षा  2202011040300   
300830         सामान्य शिक्षा  2202011040300   
301430         सामान्य शिक्षा  2202011120102   
298415         सामान्य शिक्षा  2202010010400   
300337         सामान्य शिक्षा  2202011040300   
300972         सामान्य शिक्षा  2202011050300   
299531         सामान्य शिक्षा  2202011023101   
299610         सामान्य शिक्षा  2202011023104   

                                  Scheme Code Description  \
301748                       छात्र - छात्राओं को फल वितरण   
301465               कुकिंग लागत आदि (के.60/रा.40-के+रा.)   
299996            क्षेत्रीय निरीक्षण कर्मचारीवर्ग (पुरूष)   
300830            क्षेत्रीय निरीक्षण कर्मचारीवर्ग (पुरूष)   
301430  खाद्यान्न तथा प्रबन्धन व्यय (के.60/रा.40-के.+रा.)   
298415                         बेसिक शिक्षा का लेखा संगठन   
300337            क्षेत्रीय निरीक्षण कर्मचारीवर्ग (पुरूष)   
300972  अनौपचारिक शिक्षा के अन्तर्गत परियोजनाधिकारी / ...   
299531  परिषदीय विद्यालयों तथा सहायता प्राप्त अशासकीय ...   
299610  अलाभित समूह व दुर्बल वर्ग के छात्र-छात्राओं को...   

        Standard Object Code        Standard Object Description  \
301748                    20  सहायता अनुदान -सामान्य (गैर वेतन)   
301465                    20  सहायता अनुदान -सामान्य (गैर वेतन)   
299996                    11    लेखन सामग्री और फार्मों की छपाई   
300830                    38                     अन्तरिम सहायता   
301430                    20  सहायता अनुदान -सामान्य (गैर वेतन)   
298415                     1                               वेतन   
300337                     3                       मंहगाई भत्ता   
300972                    49                      चिकित्सा व्यय   
299531                    20  सहायता अनुदान -सामान्य (गैर वेतन)   
299610                    20  सहायता अनुदान -सामान्य (गैर वेतन)   

       Plan / Non-Plan Voted / Charged fiscal_year  Progressive Allotment  \
301748               N               V   2017-2018             19599393.0   
301465               N               V   2017-2018            276264000.0   
299996               N               V   2017-2018                 1500.0   
300830               N               V   2017-2018                    0.0   
301430               N          

In [42]:
# Separating data consisting of secondary education only
secondary_school_df = df[df['Grant Head Description'] == 'शिक्षा विभाग (माध्यमिक शिक्षा)']

In [43]:
secondary_school_df.shape

(10650, 20)

In [44]:
secondary_school_df['Major Head Code'].unique()

array([2071, 2202, 2204, 2205, 4202])

In [45]:
secondary_school_df['Major Head Description'].unique()

array(['पेंशन तथा अन्य सेवा निवृत्ति हित लाभ', 'सामान्य शिक्षा',
       'खेल कूद तथा युवा सेवायें', 'कला एवं संस्कृति', nan], dtype=object)

In [46]:
secondary_school_df = secondary_school_df[secondary_school_df['Major Head Description'] == 'सामान्य शिक्षा']

In [47]:
secondary_school_df.shape

(8349, 20)

In [48]:
secondary_school_df['Major Head Code'].unique()

array([2202])

In [49]:
secondary_school_df.sample(10)

Division Code Division Description  Treasury Code         Treasury  \
306787         2000.0         KANPUR NAGAR           62.0     KANPUR DEHAT   
307664          400.0         MEERUT SADAR            4.0     MEERUT SADAR   
303370         3300.0                BASTI           67.0  SIDDHARTH NAGAR   
309315         3300.0                BASTI           33.0            BASTI   
307625          400.0         MEERUT SADAR            4.0     MEERUT SADAR   
307773         1400.0            MORADABAD           14.0        MORADABAD   
308524          200.0           SAHARANPUR           91.0           SHAMLI   
303938          400.0         MEERUT SADAR            4.0     MEERUT SADAR   
308021         2200.0            ALLAHABAD           53.0       PRATAPGARH   
305591          800.0                 AGRA           10.0             ETAH   

       Grant Number          Grant Head Description  Major Head Code  \
306787           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
307664           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
303370           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
309315           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
307625           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
307773           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
308524           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
303938           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
308021           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
305591           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   

       Major Head Description    Scheme Code  \
306787         सामान्य शिक्षा  2202021090103   
307664         सामान्य शिक्षा  2202021090103   
303370         सामान्य शिक्षा  2202020010400   
309315         सामान्य शिक्षा  2202021090300   
307625         सामान्य शिक्षा  2202021090103   
307773         सामान्य शिक्षा  2202021090103   
308524         सामान्य शिक्षा  2202021090103   
303938         सामान्य शिक्षा  2202021080400   
308021         सामान्य शिक्षा  2202021090103   
305591         सामान्य शिक्षा  2202021090103   

                                  Scheme Code Description  \
306787  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
307664  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
303370                माध्यमिक शिक्षा विभाग का लेखा संगठन   
309315                                    बालक एवं बालिका   
307625  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
307773  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
308524  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
303938        माध्यमिक शिक्षा परिषद के क्षेत्रीय कार्यालय   
308021  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
305591  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   

        Standard Object Code      Standard Object Description Plan / Non-Plan  \
306787                    38                   अन्तरिम सहायता               N   
307664                    49                    चिकित्सा व्यय               N   
303370                     4                      यात्रा व्यय               N   
309315                    11  लेखन सामग्री और फार्मों की छपाई               N   
307625                     1                             वेतन               N   
307773                    38                   अन्तरिम सहायता               N   
308524                    38                   अन्तरिम सहायता               N   
303938                     1                             वेतन               N   
308021                    38                   अन्तरिम सहायता               N   
305591                     3                     मंहगाई भत्ता               N   

       Voted / Charged fiscal_year  Progressive Allotment  \
306787               V   2017-2018                    0.0   
307664               V   2017-2018               104110.0   
303370               V   2017-2018                22000.0   
309315             

In [50]:
# concatening primary and secondary school education to get our required dataframe
school_df = pd.concat([primary_school_df, secondary_school_df])

In [51]:
school_df.shape

(12869, 20)

In [52]:
school_df['Major Head Description'].unique()

array(['सामान्य शिक्षा'], dtype=object)

In [56]:
# Required data frame
school_df.sample(10)

Division Code Division Description  Treasury Code         Treasury  \
303579          400.0         MEERUT SADAR            4.0     MEERUT SADAR   
306320         3200.0            GORAKHPUR           32.0        GORAKHPUR   
305458         4300.0        LUCKNOW COLL.           89.0  CSMAHARAJ NAGAR   
298839         3400.0             AZAMGARH           66.0              MAU   
305871         2200.0            ALLAHABAD           21.0         FATEHPUR   
298981         3200.0            GORAKHPUR           70.0      MAHARAJGANJ   
304239         4900.0             FAIZABAD           74.0    AMBEDKARNAGAR   
304558         5000.0                GONDA           51.0         BAHRAICH   
304537          400.0         MEERUT SADAR           83.0    BAGHPAT SADAR   
310504         4300.0        LUCKNOW COLL.           60.0       LUCKNOW-JB   

       Grant Number          Grant Head Description  Major Head Code  \
303579           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
306320           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
305458           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
298839           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
305871           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
298981           71  शिक्षा विभाग (प्राथमिक शिक्षा)             2202   
304239           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
304558           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
304537           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   
310504           72  शिक्षा विभाग (माध्यमिक शिक्षा)             2202   

       Major Head Description    Scheme Code  \
303579         सामान्य शिक्षा  2202021071300   
306320         सामान्य शिक्षा  2202021090103   
305458         सामान्य शिक्षा  2202021090103   
298839         सामान्य शिक्षा  2202011010300   
305871         सामान्य शिक्षा  2202021090103   
298981         सामान्य शिक्षा  2202011020300   
304239         सामान्य शिक्षा  2202021090103   
304558         सामान्य शिक्षा  2202021090103   
304537         सामान्य शिक्षा  2202021090103   
310504         सामान्य शिक्षा  2202050010300   

                                  Scheme Code Description  \
303579  हाई स्कूल और इन्टर छात्र वृत्तियों की दरों में...   
306320  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
305458  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
298839                           राजकीय प्राथमिक विद्यालय   
305871  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
298981  उत्तर प्रदेश बेसिक शिक्षा परिषद द्वारा संचालित...   
304239  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
304558  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
304537  राष्ट्रीय माध्यमिक शिक्षा अभियान (के.60/रा.40-...   
310504                                     उर्दू निदेशालय   

        Standard Object Code        Standard Object Description  \
303579                    21        छात्रवृत्तियां और छात्रवेतन   
306320                    50                        मंहगाई वेतन   
305458                     4                        यात्रा व्यय   
298839                    51                         वर्दी व्यय   
305871                    50                        मंहगाई वेतन   
298981                    20  सहायता अनुदान -सामान्य (गैर वेतन)   
304239                     6                         अन्य भत्ते   
304558                     3                       मंहगाई भत्ता   
304537                    52  पुनरीक्षित वेतन का अवशेष (राजकीय)   
310504                    13                    टेलीफोन पर व्यय   

       Plan / Non-Plan Voted / Charged fiscal_year  Progressive Allotment  \
303579               N               V   2017-2018                19680.0   
306320               P               V   2017-2018                    0.0   
305458               N               V   2017-2018               150000.0   
298839               N               V   2017-2018                    0.0   
305871               N          

In [54]:
# taking only those columns which are needed
school_df.isnull().sum()

Division Code                                          0
Division Description                                   0
Treasury Code                                          0
Treasury                                               0
Grant Number                                           0
Grant Head Description                                 0
Major Head Code                                        0
Major Head Description                                 0
Scheme Code                                            0
Scheme Code Description                                0
Standard Object Code                                   0
Standard Object Description                            0
Plan / Non-Plan                                        0
Voted / Charged                                        0
fiscal_year                                            0
Progressive Allotment                                  0
Actual Progressive Expenditure upto month (October)    0
Provisional Current Month Expen

In [57]:
school_df['Provisional Current Month Expenditure(November)'].unique()

array([0])

In [58]:
# taking only those columns which are needed from df
school_df = school_df[['Grant Head Description', 'Progressive Allotment', 'Total Expenditure Upto Month (November)', '% A/E']]

In [59]:
school_df.sample(10)

Grant Head Description  Progressive Allotment  \
303149  शिक्षा विभाग (माध्यमिक शिक्षा)                70000.0   
310544  शिक्षा विभाग (माध्यमिक शिक्षा)             10300000.0   
309979  शिक्षा विभाग (माध्यमिक शिक्षा)               168088.0   
306538  शिक्षा विभाग (माध्यमिक शिक्षा)               900000.0   
302937  शिक्षा विभाग (माध्यमिक शिक्षा)                    0.0   
309847  शिक्षा विभाग (माध्यमिक शिक्षा)                    0.0   
301020  शिक्षा विभाग (प्राथमिक शिक्षा)                18600.0   
308172  शिक्षा विभाग (माध्यमिक शिक्षा)             12500000.0   
308560  शिक्षा विभाग (माध्यमिक शिक्षा)                    0.0   
299915  शिक्षा विभाग (प्राथमिक शिक्षा)                 1500.0   

        Total Expenditure Upto Month (November)   % A/E  
303149                                  48040.0   68.63  
310544                                6951680.0   67.49  
309979                                 168088.0  100.00  
306538                                 510447.0   56.72  
302937                                      0.0    0.00  
309847                                      0.0    0.00  
301020                                  23800.0  127.96  
308172                               12448424.0   99.59  
308560                                  77600.0    0.00  
299915                                   1500.0  100.00

In [63]:
school_df.shape

(12869, 4)

In [64]:
df.shape

(375136, 4)

### 1.Calculate the share of expenditure on school education incurred by various departments/ministries. 

In [68]:
#this will be calculated division of (sum of progressive allotme)
df['Progressive Allotment'] = df.sum(axis = 1)

<ipython-input-68-ab848a3214cb>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['Progressive Allotment'] = df.sum(axis = 1)
